{% set name = "pycognito" %}
{% set version = "2022.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 40b0e1c1b3847fc8f06fe284beaee4639e3e53d8fc2ec9b281db3e0f0f34912d

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - boto3 >=1.10.49
    - envs >=1.3
    - python >=3.6
    - python-jose >=3.2.0
    - requests >=2.22.0

test:
  imports:
    - pycognito

about:
  home: https://github.com/pvizeli/pycognito
  license: Apache-2.0
  license_file: LICENSE
  summary: Python class to integrate Boto3's Cognito client so it is easy to login users. With SRP support.
  doc_url: https://github.com/pvizeli/pycognito/blob/master/README.md
  dev_url: https://github.com/pvizeli/pycognito

extra:
  recipe-maintainers:
    - kellpossible
